# Generated by Django 3.1.4 on 2021-01-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_auto_20210104_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_registered',
            name='location',
            field=models.CharField(default='NOT PROVIDED', max_length=140),
        ),
    ]
