# Generated by Django 3.1.4 on 2021-01-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0003_events_registered_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_registered',
            name='host_mobileno',
            field=models.IntegerField(default='0000000000'),
        ),
        migrations.AddField(
            model_name='events_registered',
            name='host_password',
            field=models.CharField(default='hostPass', max_length=50),
        ),
    ]
