# Generated by Django 3.1.4 on 2021-01-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0006_auto_20210120_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant_registrations',
            old_name='event_id',
            new_name='eventId',
        ),
    ]
