# Generated by Django 3.1.4 on 2021-01-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event_details',
            new_name='events_registered',
        ),
    ]
