# Generated by Django 3.1.4 on 2021-01-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0005_participant_registrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_registered',
            name='host_mobileno',
            field=models.PositiveIntegerField(default='0000000000'),
        ),
        migrations.AlterField(
            model_name='participant_registrations',
            name='event_id',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='participant_registrations',
            name='participant_mobileno',
            field=models.PositiveIntegerField(default='0000000000'),
        ),
        migrations.AlterField(
            model_name='participant_registrations',
            name='participant_total',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
